---
title: "PS270 Final Project"
author: "Fayzaan Virk"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I'm not really sure what to do for the final project or what the scope of it is. I did have an idea about the mayoral race in Minneapolis. One of the candidates, Omar Fateh, was Somali, but I saw somewhere that only about half of the Somali population in Minneapolis voted for him and the rest voted for the incumbent Jacob Frey. I wanted to see if I could find data for this and why he split his own community's vote.

## My Research Question

Unfortunately, I was not able to find any data for my above thoughts about the Minneapolis election. Luckily, I had a backup plan. I have seen conservative commentators like Charlie Kirk and Ben Shapiro ask "Is diversity really our strength?" I want to investigate this question. Specifically, I'm going to focus on racial diversity and immigration. My research question is: Do immigrants increase the economic output of their communities? My hypothesis is that immigrants do increase the economic activity in their communities because 1) they are willing to do low-paying jobs (eg. dishwasher, janitor) that are necessary but not appealing to native-born citizens and 2) they bring a diversity of ideas and experiences that can lead to new and effective business ventures. My explanatory variable will be the proportion of immigrants in each US county. This is collected by the US Census Bureau (https://www.census.gov/library/stories/2024/04/where-do-immigrants-live.html). County level data is also provided by the Migration Policy Institute. If I cannot find county level data, I will use data for each state. If I have time, I would also like to break down immigrants by country of origin and by first, second, and third generation, but I will need to find more data for this. My outcome variable will be several different economic indicators. I was planning to look at median income and home price, standard of living, and GDP per capita (if that is available at the county level). If I have time, I can look at social factors as well like crime rate, high school graduation rate, and happiness to gain a more wholistic answer to my overarching question: "Is diversity really our strength?" A pattern of increased economic output like higher median income or lower unemployment rate in counties with high proportion of immigrants would support my hypothesis. A negative or close to zero correlation would disprove my hypothesis.